import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.7
dynamic_title = true
#decorations = "None"
blur = true
dynamic_padding = false

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 5
y = 10

