import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
[window]
dynamic_title = true
decorations = "None"
blur = true
dynamic_padding = false

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 0
y = 0

# [env]
# TERM="tmux-256color"
